[2025-01-18T13:43:20.504+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:20.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:20.539+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:20.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:20.575+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:20.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6, in <module>
    sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath())))
TypeError: abspath() missing 1 required positional argument: 'path'
[2025-01-18T13:43:20.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:20.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.175 seconds
[2025-01-18T13:43:23.535+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:23.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:23.540+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:23.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:23.550+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:23.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6, in <module>
    sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath(__file))))
NameError: name '__file' is not defined. Did you mean: '__file__'?
[2025-01-18T13:43:23.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:23.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.087 seconds
[2025-01-18T13:43:24.543+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:24.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:24.546+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:24.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:24.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:24.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.033 seconds
[2025-01-18T13:43:27.622+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:27.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:27.701+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:27.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:27.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:27.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.178 seconds
[2025-01-18T13:43:47.150+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:47.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:47.173+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:47.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:47.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:47.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.159 seconds
[2025-01-18T13:43:54.456+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:54.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:54.463+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:54.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:54.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:54.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.101 seconds
[2025-01-18T13:43:56.559+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:56.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:56.579+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:56.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:56.594+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:56.590+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    'owner' : 
            ^
SyntaxError: expression expected after dictionary key and ':'
[2025-01-18T13:43:56.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:56.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.112 seconds
[2025-01-18T13:43:58.665+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:58.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:43:58.674+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:43:58.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:58.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:43:58.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.066 seconds
[2025-01-18T13:44:04.859+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:04.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:04.867+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:04.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:04.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:04.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
[2025-01-18T13:44:11.017+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:11.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:11.024+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:11.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:11.032+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:11.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 9
    'start_date'
               ^
SyntaxError: ':' expected after dictionary key
[2025-01-18T13:44:11.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:11.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.061 seconds
[2025-01-18T13:44:12.174+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:12.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:12.179+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:12.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:12.184+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:12.182+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 9
    'start_date' : 
                 ^
SyntaxError: expression expected after dictionary key and ':'
[2025-01-18T13:44:12.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:12.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.045 seconds
[2025-01-18T13:44:18.314+0000] {processor.py:186} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:18.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:18.320+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:18.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:18.327+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:18.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 9, in <module>
    'start_date' : datetime()
TypeError: function missing required argument 'year' (pos 1)
[2025-01-18T13:44:18.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:18.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2025-01-18T13:44:25.590+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:25.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:25.598+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:25.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:25.616+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:25.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 9, in <module>
    'start_date' : datetime(2024,)
TypeError: function missing required argument 'month' (pos 2)
[2025-01-18T13:44:25.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:25.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.120 seconds
[2025-01-18T13:44:30.696+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:30.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:30.705+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:30.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:30.715+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:30.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 9, in <module>
    'start_date' : datetime(2024,0)
TypeError: function missing required argument 'day' (pos 3)
[2025-01-18T13:44:30.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:30.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.071 seconds
[2025-01-18T13:44:32.818+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:32.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:32.824+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:32.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:32.831+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:32.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 9, in <module>
    'start_date' : datetime(2024,1,)
TypeError: function missing required argument 'day' (pos 3)
[2025-01-18T13:44:32.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:32.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
[2025-01-18T13:44:37.902+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:37.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:37.915+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:37.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:37.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:37.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.068 seconds
[2025-01-18T13:44:53.287+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:53.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:53.292+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:53.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:53.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:53.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.061 seconds
[2025-01-18T13:44:58.491+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:58.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:44:58.498+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:58.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:58.509+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:44:58.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 12, in <module>
    file_postfix()
NameError: name 'file_postfix' is not defined
[2025-01-18T13:44:58.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:44:58.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.083 seconds
[2025-01-18T13:45:02.613+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:02.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:02.626+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:02.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:02.637+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:02.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 12, in <module>
    file_postfi
NameError: name 'file_postfi' is not defined
[2025-01-18T13:45:02.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:02.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.090 seconds
[2025-01-18T13:45:05.746+0000] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:05.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:05.754+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:05.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:05.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:05.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.062 seconds
[2025-01-18T13:45:11.970+0000] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:11.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:11.977+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:11.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:11.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:12.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.053 seconds
[2025-01-18T13:45:13.064+0000] {processor.py:186} INFO - Started process (PID=54) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:13.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:13.074+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:13.073+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:13.084+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:13.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 12
    file_postfix = datetime.now().
                                  ^
SyntaxError: invalid syntax
[2025-01-18T13:45:13.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:13.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.077 seconds
[2025-01-18T13:45:18.214+0000] {processor.py:186} INFO - Started process (PID=55) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:18.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:18.221+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:18.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:18.229+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:18.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 12, in <module>
    file_postfix = datetime.now().strftime()
TypeError: strftime() missing required argument 'format' (pos 1)
[2025-01-18T13:45:18.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:18.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.069 seconds
[2025-01-18T13:45:27.405+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:27.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:27.413+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:27.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:27.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:27.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2025-01-18T13:45:30.526+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:30.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:30.538+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:30.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:30.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:30.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2025-01-18T13:45:33.679+0000] {processor.py:186} INFO - Started process (PID=58) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:33.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:33.687+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:33.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:33.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:33.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.065 seconds
[2025-01-18T13:45:36.756+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:36.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:36.782+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:36.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:36.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:36.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.094 seconds
[2025-01-18T13:45:43.012+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:43.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:43.035+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:43.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:43.045+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:43.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 14
    dag = 
          ^
SyntaxError: invalid syntax
[2025-01-18T13:45:43.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:43.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.087 seconds
[2025-01-18T13:45:48.161+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:48.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:48.167+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:48.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:48.174+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:48.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 14, in <module>
    dag = DAG()
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2025-01-18T13:45:48.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:48.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.058 seconds
[2025-01-18T13:45:53.317+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:53.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:53.323+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:53.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:53.330+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:53.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 14, in <module>
    dag = DAG(
TypeError: DAG.__init__() missing 1 required positional argument: 'dag_id'
[2025-01-18T13:45:53.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:53.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.071 seconds
[2025-01-18T13:45:58.492+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:58.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:45:58.507+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:58.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:58.519+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:45:58.517+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 16
    )
    ^
SyntaxError: invalid syntax
[2025-01-18T13:45:58.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:45:58.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.077 seconds
[2025-01-18T13:46:02.558+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:02.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:02.565+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:02.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:02.586+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:02.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 14, in <module>
    dag = DAG(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-18T13:46:02.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:02.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.101 seconds
[2025-01-18T13:46:07.705+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:07.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:07.713+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:07.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:07.803+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:08.063+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.062+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:etl_reddit_pipeline
[2025-01-18T13:46:08.068+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.068+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:etl_reddit_pipeline
[2025-01-18T13:46:08.071+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.071+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:etl_reddit_pipeline
[2025-01-18T13:46:08.073+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.073+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:etl_reddit_pipeline
[2025-01-18T13:46:08.075+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.075+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:etl_reddit_pipeline
[2025-01-18T13:46:08.078+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.077+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:etl_reddit_pipeline
[2025-01-18T13:46:08.080+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.080+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:etl_reddit_pipeline
[2025-01-18T13:46:08.080+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.080+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:46:08.101+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.101+0000] {dag.py:3262} INFO - Creating ORM DAG for etl_reddit_pipeline
[2025-01-18T13:46:08.120+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:08.120+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2025-01-18T13:46:08.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.450 seconds
[2025-01-18T13:46:10.234+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:10.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:10.242+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:10.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:10.263+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:10.290+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:10.289+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:46:10.307+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:10.307+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2025-01-18T13:46:10.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.108 seconds
[2025-01-18T13:46:17.371+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:17.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:17.381+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:17.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:17.400+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:17.398+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    )
    ^
SyntaxError: invalid syntax
[2025-01-18T13:46:17.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:17.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.068 seconds
[2025-01-18T13:46:21.517+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:21.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:21.525+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:21.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:21.534+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:21.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 16
    default_args=def
                 ^^^
SyntaxError: invalid syntax
[2025-01-18T13:46:21.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:21.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2025-01-18T13:46:23.567+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:23.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:23.574+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:23.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:23.593+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:23.604+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:23.604+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:46:23.623+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:23.623+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2025-01-18T13:46:23.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.075 seconds
[2025-01-18T13:46:26.742+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:26.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:26.748+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:26.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:26.766+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:26.807+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:26.807+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:46:26.841+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:26.841+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to None, run_after=None
[2025-01-18T13:46:26.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.134 seconds
[2025-01-18T13:46:33.999+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:34.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:34.007+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:34.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:34.015+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:34.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 18
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T13:46:34.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:34.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.080 seconds
[2025-01-18T13:46:38.083+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:38.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:38.092+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:38.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:38.099+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:38.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:46:38.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:38.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.088 seconds
[2025-01-18T13:46:40.214+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:40.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:40.231+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:40.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:40.239+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:40.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:46:40.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:40.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.058 seconds
[2025-01-18T13:46:46.464+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:46.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:46.471+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:46.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:46.482+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:46.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:46:46.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:46.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.074 seconds
[2025-01-18T13:46:48.562+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:48.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:46:48.569+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:48.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:48.587+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:46:48.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:46:48.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:46:48.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.058 seconds
[2025-01-18T13:47:06.915+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:06.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:06.923+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:06.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:06.935+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:06.932+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:06.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:06.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2025-01-18T13:47:07.965+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:07.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:07.970+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:07.970+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:07.975+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:07.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:07.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:08.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.053 seconds
[2025-01-18T13:47:09.051+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:09.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:09.056+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:09.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:09.063+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:09.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:09.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:09.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.040 seconds
[2025-01-18T13:47:13.171+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:13.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:13.183+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:13.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:13.192+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:13.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:13.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:13.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.074 seconds
[2025-01-18T13:47:16.218+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:16.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:16.221+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:16.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:16.226+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:16.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:16.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:16.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.037 seconds
[2025-01-18T13:47:18.252+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:18.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:18.257+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:18.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:18.263+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:18.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:18.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:18.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.045 seconds
[2025-01-18T13:47:21.342+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:21.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:21.346+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:21.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:21.351+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:21.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 17
    schedule_interval=@daily,
                      ^
SyntaxError: invalid syntax
[2025-01-18T13:47:21.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:21.368+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.036 seconds
[2025-01-18T13:47:27.475+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:27.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:27.485+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:27.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:27.518+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:27.604+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:27.604+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:47:27.620+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:27.620+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to 2025-01-17 00:00:00+00:00, run_after=2025-01-18 00:00:00+00:00
[2025-01-18T13:47:27.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.189 seconds
[2025-01-18T13:47:36.680+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:36.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:36.698+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:36.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:36.730+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:36.773+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:36.773+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:47:36.806+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:36.806+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to 2025-01-17 00:00:00+00:00, run_after=2025-01-18 00:00:00+00:00
[2025-01-18T13:47:36.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.181 seconds
[2025-01-18T13:47:49.061+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:49.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:49.070+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:49.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:49.101+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:49.166+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:49.166+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:47:49.186+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:49.186+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to 2025-01-17 00:00:00+00:00, run_after=2025-01-18 00:00:00+00:00
[2025-01-18T13:47:49.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.153 seconds
[2025-01-18T13:47:55.202+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:55.205+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:47:55.210+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:55.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:55.243+0000] {processor.py:925} INFO - DAG(s) 'etl_reddit_pipeline' retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:47:55.259+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:55.259+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-18T13:47:55.287+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:47:55.287+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_reddit_pipeline to 2025-01-17 00:00:00+00:00, run_after=2025-01-18 00:00:00+00:00
[2025-01-18T13:47:55.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.112 seconds
[2025-01-18T13:48:02.524+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:02.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:02.533+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:02.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:02.550+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:02.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = python
NameError: name 'python' is not defined
[2025-01-18T13:48:02.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:02.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.100 seconds
[2025-01-18T13:48:14.767+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:14.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:14.775+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:14.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:14.792+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:14.788+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOpeartor
NameError: name 'PythonOpeartor' is not defined
[2025-01-18T13:48:14.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:14.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.088 seconds
[2025-01-18T13:48:16.976+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:16.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:16.983+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:16.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:16.993+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:16.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:16.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:17.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2025-01-18T13:48:19.049+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:19.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:19.056+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:19.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:19.070+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:19.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator()
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:19.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:19.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.069 seconds
[2025-01-18T13:48:24.354+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:24.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:24.361+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:24.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:24.379+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:24.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:24.381+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:24.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.074 seconds
[2025-01-18T13:48:27.497+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:27.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:27.504+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:27.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:27.523+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:27.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:27.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:27.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.068 seconds
[2025-01-18T13:48:31.668+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:31.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:31.676+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:31.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:31.698+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:31.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:31.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:31.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.070 seconds
[2025-01-18T13:48:35.940+0000] {processor.py:186} INFO - Started process (PID=94) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:35.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:35.949+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:35.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:35.965+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:35.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 25
    )
    ^
SyntaxError: invalid syntax
[2025-01-18T13:48:35.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:35.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.072 seconds
[2025-01-18T13:48:39.032+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:39.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:39.056+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:39.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:39.082+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:39.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:39.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:39.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.221 seconds
[2025-01-18T13:48:45.240+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:45.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:45.248+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:45.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:45.264+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:45.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:45.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:45.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.082 seconds
[2025-01-18T13:48:56.574+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:56.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:48:56.578+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:56.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:56.592+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:48:56.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:48:56.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:48:56.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2025-01-18T13:49:01.705+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:01.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:49:01.709+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:01.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:01.724+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:01.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:49:01.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:01.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.074 seconds
[2025-01-18T13:49:06.810+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:06.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:49:06.817+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:06.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:06.836+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:06.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 23, in <module>
    extract = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2025-01-18T13:49:06.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:06.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.082 seconds
[2025-01-18T13:49:16.034+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:16.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:49:16.038+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:16.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:16.046+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:16.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T13:49:16.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:16.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.047 seconds
[2025-01-18T13:49:17.068+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:17.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:49:17.072+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:17.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:17.082+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:17.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T13:49:17.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:17.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.044 seconds
[2025-01-18T13:49:20.184+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:20.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T13:49:20.188+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:20.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:20.194+0000] {logging_mixin.py:190} INFO - [2025-01-18T13:49:20.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T13:49:20.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T13:49:20.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.042 seconds
[2025-01-18T14:04:41.034+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:04:41.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T14:04:41.037+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:04:41.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:04:41.043+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:04:41.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T14:04:41.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:04:41.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.042 seconds
[2025-01-18T14:05:11.517+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:05:11.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T14:05:11.521+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:05:11.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:05:11.530+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:05:11.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T14:05:11.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:05:11.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.071 seconds
[2025-01-18T14:21:05.841+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:21:05.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T14:21:05.843+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:21:05.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:21:05.849+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:21:05.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T14:21:05.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:21:05.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.035 seconds
[2025-01-18T14:37:00.952+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:37:00.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T14:37:00.955+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:37:00.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:37:00.962+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:37:00.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T14:37:00.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:37:00.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.055 seconds
[2025-01-18T14:52:57.164+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:52:57.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T14:52:57.169+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:52:57.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:52:57.176+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:52:57.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T14:52:57.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:52:57.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.044 seconds
[2025-01-18T14:53:27.699+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:53:27.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T14:53:27.703+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:53:27.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:53:27.710+0000] {logging_mixin.py:190} INFO - [2025-01-18T14:53:27.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T14:53:27.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T14:53:27.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.051 seconds
[2025-01-18T15:09:22.972+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:09:22.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T15:09:22.977+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:09:22.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:09:23.002+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:09:23.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T15:09:23.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:09:23.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.066 seconds
[2025-01-18T15:25:17.440+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:25:17.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T15:25:17.443+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:25:17.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:25:17.449+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:25:17.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T15:25:17.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:25:17.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.045 seconds
[2025-01-18T15:25:47.797+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:25:47.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T15:25:47.813+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:25:47.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:25:47.826+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:25:47.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T15:25:47.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:25:47.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.066 seconds
[2025-01-18T15:41:43.425+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:41:43.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T15:41:43.430+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:41:43.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:41:43.437+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:41:43.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T15:41:43.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:41:43.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.066 seconds
[2025-01-18T15:50:38.637+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:50:38.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T15:50:38.640+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:50:38.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:50:38.646+0000] {logging_mixin.py:190} INFO - [2025-01-18T15:50:38.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T15:50:38.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T15:50:38.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2025-01-18T16:06:34.109+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:06:34.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:06:34.117+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:06:34.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:06:34.128+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:06:34.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:06:34.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:06:34.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.067 seconds
[2025-01-18T16:07:04.626+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:07:04.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:07:04.630+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:07:04.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:07:04.637+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:07:04.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:07:04.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:07:04.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2025-01-18T16:22:59.155+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:22:59.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:22:59.162+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:22:59.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:22:59.168+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:22:59.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:22:59.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:22:59.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.058 seconds
[2025-01-18T16:38:54.560+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:38:54.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:38:54.562+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:38:54.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:38:54.568+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:38:54.567+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:38:54.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:38:54.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.039 seconds
[2025-01-18T16:39:25.169+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:39:25.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:39:25.173+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:39:25.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:39:25.183+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:39:25.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:39:25.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:39:25.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.070 seconds
[2025-01-18T16:51:53.014+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:51:53.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:51:53.017+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:51:53.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:51:53.023+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:51:53.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:51:53.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:51:53.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.044 seconds
[2025-01-18T16:55:15.564+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:55:15.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T16:55:15.568+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:55:15.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:55:15.575+0000] {logging_mixin.py:190} INFO - [2025-01-18T16:55:15.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T16:55:15.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T16:55:15.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.066 seconds
[2025-01-18T17:11:11.014+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:11:11.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T17:11:11.018+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:11:11.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:11:11.024+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:11:11.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T17:11:11.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:11:11.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2025-01-18T17:27:05.361+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:27:05.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T17:27:05.364+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:27:05.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:27:05.370+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:27:05.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T17:27:05.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:27:05.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2025-01-18T17:43:01.554+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:43:01.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T17:43:01.557+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:43:01.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:43:01.563+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:43:01.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T17:43:01.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:43:01.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.036 seconds
[2025-01-18T17:43:32.149+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:43:32.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T17:43:32.154+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:43:32.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:43:32.162+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:43:32.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T17:43:32.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:43:32.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.067 seconds
[2025-01-18T17:52:45.751+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:52:45.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T17:52:45.755+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:52:45.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:52:45.762+0000] {logging_mixin.py:190} INFO - [2025-01-18T17:52:45.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T17:52:45.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T17:52:45.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.052 seconds
[2025-01-18T18:08:41.139+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:08:41.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T18:08:41.142+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:08:41.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:08:41.148+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:08:41.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T18:08:41.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:08:41.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.053 seconds
[2025-01-18T18:09:11.724+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:09:11.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T18:09:11.728+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:09:11.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:09:11.735+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:09:11.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T18:09:11.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:09:11.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.067 seconds
[2025-01-18T18:25:06.800+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:25:06.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T18:25:06.803+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:25:06.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:25:06.809+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:25:06.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T18:25:06.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:25:06.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.044 seconds
[2025-01-18T18:42:24.227+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:42:24.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T18:42:24.230+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:42:24.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:42:24.235+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:42:24.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T18:42:24.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:42:24.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2025-01-18T18:42:55.708+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:42:55.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T18:42:55.713+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:42:55.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:42:55.722+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:42:55.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T18:42:55.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:42:55.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.073 seconds
[2025-01-18T18:53:47.238+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:53:47.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T18:53:47.242+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:53:47.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:53:47.249+0000] {logging_mixin.py:190} INFO - [2025-01-18T18:53:47.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T18:53:47.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T18:53:47.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.043 seconds
[2025-01-18T19:09:43.358+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:09:43.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T19:09:43.367+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:09:43.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:09:43.372+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:09:43.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T19:09:43.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:09:43.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.046 seconds
[2025-01-18T19:10:13.936+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:10:13.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T19:10:13.941+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:10:13.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:10:13.952+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:10:13.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T19:10:13.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:10:13.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.069 seconds
[2025-01-18T19:26:08.212+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:26:08.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T19:26:08.215+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:26:08.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:26:08.223+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:26:08.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T19:26:08.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:26:08.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2025-01-18T19:42:03.569+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:42:03.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T19:42:03.573+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:42:03.573+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:42:03.587+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:42:03.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T19:42:03.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:42:03.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.051 seconds
[2025-01-18T19:54:30.732+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:54:30.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T19:54:30.735+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:54:30.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:54:30.742+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:54:30.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T19:54:30.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:54:30.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.042 seconds
[2025-01-18T19:55:01.235+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:55:01.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T19:55:01.241+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:55:01.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:55:01.248+0000] {logging_mixin.py:190} INFO - [2025-01-18T19:55:01.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T19:55:01.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T19:55:01.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.046 seconds
[2025-01-18T20:10:56.517+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:10:56.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T20:10:56.520+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:10:56.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:10:56.526+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:10:56.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T20:10:56.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:10:56.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.042 seconds
[2025-01-18T20:26:51.774+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:26:51.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T20:26:51.779+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:26:51.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:26:51.797+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:26:51.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T20:26:51.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:26:51.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2025-01-18T20:27:22.375+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:27:22.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T20:27:22.380+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:27:22.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:27:22.387+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:27:22.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T20:27:22.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:27:22.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.065 seconds
[2025-01-18T20:43:16.866+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:43:16.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T20:43:16.869+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:43:16.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:43:16.876+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:43:16.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T20:43:16.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:43:16.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.046 seconds
[2025-01-18T20:44:54.724+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:44:54.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T20:44:54.728+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:44:54.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:44:54.736+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:44:54.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T20:44:54.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:44:54.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
[2025-01-18T20:55:45.037+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:55:45.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T20:55:45.040+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:55:45.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:55:45.057+0000] {logging_mixin.py:190} INFO - [2025-01-18T20:55:45.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T20:55:45.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T20:55:45.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2025-01-18T21:11:40.356+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:11:40.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T21:11:40.360+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:11:40.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:11:40.367+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:11:40.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T21:11:40.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:11:40.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2025-01-18T21:12:10.889+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:12:10.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T21:12:10.895+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:12:10.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:12:10.903+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:12:10.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T21:12:10.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:12:10.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.074 seconds
[2025-01-18T21:28:05.232+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:28:05.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T21:28:05.235+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:28:05.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:28:05.241+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:28:05.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T21:28:05.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:28:05.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2025-01-18T21:43:59.664+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:43:59.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T21:43:59.668+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:43:59.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:43:59.674+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:43:59.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T21:43:59.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:43:59.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.039 seconds
[2025-01-18T21:44:30.181+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:44:30.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T21:44:30.187+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:44:30.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:44:30.197+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:44:30.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T21:44:30.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:44:30.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.104 seconds
[2025-01-18T21:56:59.107+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:56:59.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T21:56:59.111+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:56:59.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:56:59.118+0000] {logging_mixin.py:190} INFO - [2025-01-18T21:56:59.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T21:56:59.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T21:56:59.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2025-01-18T22:12:47.864+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:12:47.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T22:12:47.867+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:12:47.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:12:47.874+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:12:47.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T22:12:47.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:12:47.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.055 seconds
[2025-01-18T22:28:43.268+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:28:43.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T22:28:43.272+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:28:43.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:28:43.279+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:28:43.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T22:28:43.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:28:43.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2025-01-18T22:29:13.848+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:29:13.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T22:29:13.853+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:29:13.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:29:13.860+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:29:13.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T22:29:13.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:29:13.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.070 seconds
[2025-01-18T22:45:08.262+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:45:08.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T22:45:08.265+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:45:08.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:45:08.275+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:45:08.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T22:45:08.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:45:08.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.055 seconds
[2025-01-18T22:57:38.357+0000] {processor.py:186} INFO - Started process (PID=154) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:57:38.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T22:57:38.361+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:57:38.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:57:38.376+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:57:38.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T22:57:38.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:57:38.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.050 seconds
[2025-01-18T22:58:08.901+0000] {processor.py:186} INFO - Started process (PID=155) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:58:08.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T22:58:08.905+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:58:08.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:58:08.913+0000] {logging_mixin.py:190} INFO - [2025-01-18T22:58:08.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T22:58:08.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T22:58:08.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.053 seconds
[2025-01-18T23:14:03.311+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:14:03.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T23:14:03.317+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:14:03.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:14:03.324+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:14:03.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T23:14:03.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:14:03.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.039 seconds
[2025-01-18T23:29:57.731+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:29:57.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T23:29:57.735+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:29:57.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:29:57.743+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:29:57.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T23:29:57.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:29:57.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2025-01-18T23:45:53.130+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:45:53.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T23:45:53.134+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:45:53.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:45:53.141+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:45:53.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T23:45:53.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:45:53.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.043 seconds
[2025-01-18T23:46:23.632+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:46:23.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T23:46:23.636+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:46:23.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:46:23.642+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:46:23.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T23:46:23.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:46:23.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.038 seconds
[2025-01-18T23:58:51.488+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:58:51.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-18T23:58:51.492+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:58:51.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:58:51.498+0000] {logging_mixin.py:190} INFO - [2025-01-18T23:58:51.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 27
    )
    ^
SyntaxError: positional argument follows keyword argument
[2025-01-18T23:58:51.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-18T23:58:51.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.048 seconds
